### ISSUE TITLE
When clicked away from the confirmation dialog it goes away (while in broadcasting... state)

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#204] opened 2015-09-14 22:22 UTC

**Comment by svk31** [comment] 2015-09-16 17:53
Just adding that it'll come back if you navigate to another page, and keep popping up again forever if for some reason there's no api response.

**Comment by svk31** [comment] 2015-09-18 05:52
I guess the commit for this is the cause of #218 ? Closing this and let's use the other one cause it's clearer.

**Closed as completed by svk31** 2015-09-18 05:52 UTC
