### ISSUE TITLE
Markets screen fails to load when user doesn't have an account

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#487] opened 2015-11-13 00:17 UTC
When a user first opens the web wallet, they have access to the Trade tab at the top. When they click on the Trade tab, it takes them to the list of Markets, however, if the user clicks on a Market, the loading graphic persists.

This is confusing to the user. I'd suggest a modal when the user clicks on a market that said:

"Please create an account to view the markets"

alternatively we could allow the user to view the markets but hide the BUY/SELL controls and input fields. Either way would be an acceptable solution.

**Comment by svk31** [comment] 2015-11-23 13:40
This is a duplicate of #507.

Also, the Trade link does not appear until you either create an account or follow an account. I suggest closing this and tracking in 507 instead.

**Closed as completed** 2015-11-23 14:37 UTC
Labels: duplicate
