### ISSUE TITLE
The witnesses page crash - cannot read property 'indexOf' and '_currentElement'

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#280] opened 2015-10-06 17:29 UTC
The app crashes in both Chrome and Firefox (Win 7) with these errors showing up in the console: 

--Uncaught TypeError: Cannot read property 'indexOf' of undefined
--Uncaught TypeError: Cannot read property '_currentElement' of null
--Uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.2.0.0.0.0.1.5.1.1.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like..

How to recreate:
1. Navigate to #/dashboard
2. Reload the entire web page in the browser
3. Navigate to #/markets and then to one of the markets, e.g. #/exchange/trade/AAAAAA_CORE
4. Navigate to #/explorer
5. Navigate to #/explorer/blocks
6. Navigate to #/explorer
7. Navigate to #/explorer/witnesses <---- this is when the application crashes

**Comment by valzav** [comment] 2015-10-06 17:32
Is it custom graphene-ui build? Or you are using graphene.bitshares.org http://graphene.bitshares.org/?

> On Oct 6, 2015, at 1:29 PM, neura-sx notifications@github.com wrote:
> 
> The app crashes in both Chrome and Firefox (Win 7) with these errors showing up in the console:
> 
> --Uncaught TypeError: Cannot read property 'indexOf' of undefined
> --Uncaught TypeError: Cannot read property '_currentElement' of null
> --Uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.2.0.0.0.0.1.5.1.1.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a when using tables, nesting tags like..
> 
> How to recreate:
> 1. Navigate to #/dashboard
> 2. Reload the entire web page in the browser
> 3. Navigate to #/markets and then to one of the markets, e.g. #/exchange/trade/AAAAAA_CORE
> 4. Navigate to #/explorer
> 5. Navigate to #/explorer/blocks
> 6. Navigate to #/explorer
> 7. Navigate to #/explorer/witnesses <---- this is when the application crashes
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/280.

## 

Regards,
Val

**Comment by neura-sx** [comment] 2015-10-06 17:44
I'm using https://graphene.bitshares.org
Sometimes it's hard to recreate - generally the idea is to reload the app in the browser and then visit several different pages within the app (e.g. account pages like #/account/???/overview) and after that navigate to #/explorer/witnesses.

**Comment by neura-sx** [comment] 2015-10-06 23:48
Seems to be fixed after the latest upgrade.

**Comment by svk31** [comment] 2015-10-10 18:32
An issue remains but it's a duplicate of #281 which is more specific imo, closing

**Closed as completed by svk31** 2015-10-10 18:32 UTC
