### ISSUE TITLE
"Borrow Asset" window resets on new block on some accounts

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#505] opened 2015-11-19 14:08 UTC
On one account, the "borrow asset" window resets every block:
http://162.243.185.205/images/reset_on_new_block.mp4

On another it doesn't:
http://162.243.185.205/images/account_that_works.mp4
both updating existing positions and creating a position have this bug

Conditions I've tried on the account that works:
1) no orders on any market
2) orders on one side of a market
3) orders on both sides of a market

Current conditions on the account that doesn't work:
1) orders with expiration dates on  both sides of multiple markets, am short on a different markets.

Last night, with the same accounts, this did not happen. Here's what happened since last night:
1) created short positions in two different markets
2) multiple trades in multiple markets
3) closed the short position in one of the markets

I've also tried creating a new wallet and importing my backup. This still happens on the same account

**Comment by svk31** [comment] 2015-11-19 14:11
Guess I got a bit over-zealous trying to make sure the positions updated when you switch accounts. I'll fix this today before launch.

**Comment by maqifrnswa** [comment] 2015-11-19 22:05
Thanks, but I still have the same issue in 2.0.151119 on the same account

**Comment by wmbutler** [comment] 2015-11-20 20:10
Opening and adding back as a bug in 1125 based upon most recent comments.

**Comment by svk31** [comment] 2015-11-22 08:32
I can't reproduce but I've made some more improvements to the update logic for the component. I also identified an issue where the modal did not show after switching to a different market. I've fixed that issue in another repo ref: https://github.com/valzav/react-foundation-apps/pull/1

**Comment by wmbutler** [comment] 2015-11-22 14:05
The only thing I noticed is that the slider let's you keep adding collateral even if you don't have enough BTS. So, in this case, I only have 322 BTS in my account. I think that once the collateral reaches 322 (including fees), it should stop incrementing and the remaining clooateral should get locked to 0 rather than going negative. By allowing the current behavior, you are letting the user step into an impossible situation.

![screen shot 2015-11-22 at 9 02 52 am](https://cloud.githubusercontent.com/assets/1254810/11324167/2210e680-90f8-11e5-9765-8c319539815d.png)

**Comment by svk31** [comment] 2015-11-22 19:42
Moving this to testing, situation wmbutler noticed was related to a bug in the remaining collateral balance calculation, the modal does not allow the user to make "impossible" updates.

**Closed as completed** 2015-11-25 19:57 UTC
Labels: bug
