### ISSUE TITLE
Worker Proposal voting is broken.  Can someone confirm?

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#746] opened 2016-02-20 21:35 UTC
At OpenLedger I try to vote for a worker proposal.  The UI tries to send this to the server under `get_required_fees` and gets an error (below):

``` js
[
  [
    [
      6,
      {
        "fee": {
          "amount": "0",
          "asset_id": "1.3.0"
        },
        "account": "1.2.34958",
        "owner": {
          "weight_threshold": 1,
          "account_auths": [

          ],
          "key_auths": [
            [
              "BTS6Lc3swzX43dZ5qGbNG1eyxKVgMmJHuQwWp6h57vXofUcDW2gdd",
              1
            ]
          ],
          "address_auths": [

          ]
        },
        "active": {
          "weight_threshold": 1,
          "account_auths": [

          ],
          "key_auths": [
            [
              "BTS8GimhseNzW8KhBqBr4WXySnSdE9YLN2Y9VUjdChLBHnQyTGdzb",
              1
            ]
          ],
          "address_auths": [

          ]
        },
        "new_options": {
          "memo_key": "BTS8GimhseNzW8KhBqBr4WXySnSdE9YLN2Y9VUjdChLBHnQyTGdzb",
          "voting_account": "1.2.5",
          "num_witness": 0,
          "num_committee": 0,
          "votes": [
            "2:117"
          ],
          "extensions": [

          ]
        },
        "extensions": [

        ]
      }
    ]
  ],
  "1.3.0"
]
```

Error reply:

``` js
{
  "code": 1,
  "message": "7 bad_cast_exception: Bad Cast\nInvalid cast from type 'array_type' to Object\n    {\"type\":\"array_type\"}\n    th_a  variant.cpp:575 get_object",
  "data": {
    "code": 7,
    "name": "bad_cast_exception",
    "message": "Bad Cast",
    "stack": [
      {
        "context": {
          "level": "error",
          "file": "variant.cpp",
          "line": 575,
          "method": "get_object",
          "hostname": "",
          "thread_name": "th_a",
          "timestamp": "2016-02-20T21:21:46"
        },
        "format": "Invalid cast from type '${type}' to Object",
        "data": {
          "type": "array_type"
        }
      }
    ]
  }
}
```

A transfer works fine...

**Comment by jcalfee** [comment] 2016-02-20 23:41
The transfer below (it works) .. It must be something in the vote transaction format.  I don't see any code changes that might cause this .. I'm drawing a blank on this one at the moment.

``` js
[
  [
    [
      0,
      {
        "fee": {
          "amount": "0",
          "asset_id": "1.3.0"
        },
        "from": "1.2.34958",
        "to": "1.2.34235",
        "amount": {
          "amount": "100000",
          "asset_id": "1.3.0"
        },
        "extensions": [

        ]
      }
    ]
  ],
  "1.3.0"
]
```

**Comment by roadscape** [comment] 2016-02-21 00:10
I think it's the same problem as these 2. Not clear if the issue is in GUI or cli_wallet..
https://github.com/cryptonomex/graphene-ui/issues/745
https://github.com/cryptonomex/graphene/issues/593

**Comment by abitmore** [comment] 2016-02-21 08:47
<del>I'd suggest revert the backend of OL to last version, until the hard fork date AND GUI is fixed.</del>

**Comment by abitmore** [comment] 2016-02-21 08:50
<del>I can make a patch on the witness_node to address this issue. But if you transaction got passed, imo it may cause network forking, since upgraded (block producing witnesses) will accept your transaction but non-upgraded witnesses will reject it.</del>

**Comment by abitmore** [comment] 2016-02-21 09:51
Update: it's not dangerous to enable the new format before hard fork date <b>if keep the `extensions` field empty </b>, according to @pmconrad's comment in [this thread](https://bitsharestalk.org/index.php/topic,21530.msg280675.html#msg280675). So GUi can be updated  safely.

**Comment by abitmore** [comment] 2016-02-21 10:06
@jcalfee type of the `extensions` field of `account_create_operation` and `account_update_operation` has changed from an array to a struct in witness_node-2.0.160216, so need to replace `[]` to `{}` in the GUI code.

**Comment by jcalfee** [comment] 2016-02-21 12:51
I'll rebuild the develop branch so I can get any serializer updates (there is a generated file) and close this ticket if it works.  Thanks!  Odd that `extensions` is not consistent now (the transfer has an extension [] in it too).

**Comment by jcalfee** [comment] 2016-02-21 16:29
The serialized code is the same.  Looks like the extensions have not changed since July (see link).

https://github.com/cryptonomex/graphene/blame/f85dec1c23f6bf9259ad9f15311b2e4aac4f9d44/libraries/chain/include/graphene/chain/protocol/account.hpp#L114

**Comment by valzav** [comment] 2016-02-21 16:31
Maybe this one https://github.com/bitshares/bitshares-2/commit/a1e8fc07417407525482924df6b125d95c38a06f#diff-1a2d7c55b5a8f1e2bbb1c868896c94eeL117 ?

**Comment by jcalfee** [comment] 2016-02-21 16:39
There, this change is not on the develop branch!  That explains it.. I need some branch training from @theoreticalbts ...

**Comment by abitmore** [comment] 2016-02-21 20:15
@jcalfee It's on the develop branch: https://github.com/cryptonomex/graphene/blob/develop/libraries/chain/include/graphene/chain/protocol/account.hpp#L98 and https://github.com/cryptonomex/graphene/blob/develop/libraries/chain/include/graphene/chain/protocol/account.hpp#L146

Blame link:
https://github.com/cryptonomex/graphene/blame/develop/libraries/chain/include/graphene/chain/protocol/account.hpp#L98

Make sure you're checking develop branch of [cryptonomex/graphene](https://github.com/cryptonomex/graphene) repo but not [bitshares/bitshares-2](https://github.com/bitshares/bitshares-2) repo.

**Comment by abitmore** [comment] 2016-02-21 20:20
And also master branch of [cryptonomex/graphene](https://github.com/cryptonomex/graphene) repo is abandoned imo.

**Comment by theoreticalbts** [comment] 2016-02-22 17:02
This is broken because account update operation is affected by cryptonomex/graphene#593

**Comment by svk31** [comment] 2016-02-24 17:56
Fixed in graphene core, closing.

**Closed as completed by svk31** 2016-02-24 17:56 UTC
