### ISSUE TITLE
Deposit addresses disappear when clicking on "Generate"

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#599] opened 2015-12-09 14:03 UTC
See this image: 
http://i.imgur.com/0pLzSBa.png 

I just wanted to deposit some DOGE.

**Comment by svk31** [comment] 2015-12-31 14:31
I'm guessing this was either an issue with the ccedk api or related to the bug I fixed here: https://github.com/cryptonomex/graphene-ui/commit/2851cbd24db19e731ec303c41afc458b9aa97f25

Closing since I'm unable to reproduce but do let us know if it happens again. If it does, please include any errors from the console.

**Closed as completed by svk31** 2015-12-31 14:31 UTC
Labels: bug

**Comment by kenCode-de** [comment] 2015-12-31 14:42
Thanx svk, I have not seen that issue for a while now so ur right it probably was a ccedk connection prob or something. Thanx again! :)
