### ISSUE TITLE
The vertical scroll-bar is not working properly on the market page

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#447] opened 2015-11-05 20:33 UTC
Also, the last row of market orders seems to be cut in the middle.

![iss-scroll](https://cloud.githubusercontent.com/assets/11573977/10980875/9af12818-8404-11e5-86dd-9002b7143897.png)

**Comment by wmbutler** [comment] 2015-11-06 01:47
I can't reproduce in Chrome on OSX. Please submit browser and OS version.

**Comment by neura-sx** [comment] 2015-11-06 05:34
Chrome, Win 7

**Comment by wmbutler** [comment] 2015-11-06 08:31
If anyone on the team has Chrome, Win 7 and can verify this, please comment here to confirm.

**Comment by neura-sx** [comment] 2015-11-23 06:54
This small bug is still there in 2.0.151119 release.
Only in [Chrome / Win 7].
It works fine in [Firefox / Win 7].

**Comment by wmbutler** [comment] 2015-11-23 14:21
@valzav This one is nagging. Can you please review?

**Comment by svk31** [comment] 2015-11-23 14:26
I did look at this a while back, but I couldn't get it right. The interaction between the the perfect scrollbar library and foundation flexbox is hard to get right. I think it's related to the height of the container which in this case is 100%, but not sure.

This is low priority for me though tbh, just use the scroll wheel or touchpad scrolling if you don't have a mouse..

**Comment by wmbutler** [comment] 2015-11-23 14:49
@neura-sx we are closing this out for now. May revisit at a later date,

**Closed as completed by wmbutler** 2015-11-23 14:49 UTC
Labels: bug
