### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#819] opened 2016-04-11 16:01 UTC
Version 160406 on Chrome (Windows 10)
This error renders the whole trading module unusable - the whole page becomes totally unresponsive.

It happens whenever I navigate to the market page. 
e.g. https://bitshares.openledger.info/#/market/USD_BTS

![maximum](https://cloud.githubusercontent.com/assets/11573977/14433509/d7879aa6-000e-11e6-8649-ef9942092fa9.png)

**Comment by svk31** [comment] 2016-04-11 17:02
I'm unable to reproduce this so it's a bit hard to debug. Could you expand the Uncaught RangeError messages by clicking on the little arrow on the left?

**Comment by neura-sx** [comment] 2016-04-11 21:51
Also, please note this error at the very top:
_Uncaught Error: Cannot find module "react-highcharts/bundle/highstock"_

![maximum2](https://cloud.githubusercontent.com/assets/11573977/14443560/4103c10e-0040-11e6-9b4a-85584b5ecef3.png)

**Comment by neura-sx** [comment] 2016-04-11 22:47
@svk31 I've done some more tests on different Windows 10 machines and it seems that this error has something to do with toggling between vertical and horizontal layouts for market orders. Everything works fine unless I start playing with the toggle. And once it gets stuck the only way to fix it, is to clear the local storage settings in the browser.

**Comment by svk31** [comment] 2016-04-12 16:39
The highcharts error is unrelated and has already been fixed in another commit.

I still can't reproduce this I'm afraid, but it looks to me like you've been navigating to the transfer page because that's the only place you'd get the console message "onAmountChanged". Are you sure the error is happening in the exchange?

**Comment by neura-sx** [comment] 2016-04-13 18:37
Yes, it definitely happens on the exchange page.

I think it is very specific and might be related to a particular window size and zoom factor in the browser. In my case it only happens when the zoom is set to 90% and the browser is expanded to full screen on a 1920x1200 monitor.

It does not happen on my laptop which has the same OS but a different screen size.

**Comment by neura-sx** [comment] 2016-04-13 18:44
My further experiments indicate that this bug is definitely related to the size of the browser window (both width and height). 

To recreate the bug, navigate to the exchange page, switch to the vertical layout for market orders and drag the bottom right corner of the browser window to resize it to different sizes. You will eventually stumble upon a combination of width and height that triggers the error.

Using this method I've manged to recreate the bug on my laptop.

**Comment by svk31** [comment] 2016-05-24 19:10
Closing since I've never been able to reproduce and have had no other reports of this.

**Closed as completed by svk31** 2016-05-24 19:10 UTC
