### ISSUE TITLE
active key/owner key of collateral-holder account doesn't show in GUI, unable to vote

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#660] opened 2016-01-10 16:44 UTC

**Comment by svk31** [comment] 2016-01-28 19:49
I don't have access to a collateral-holder account so I was unable to verify that the pubkey -> priv key lookup works, but @xeroc will try to verify it tomorrow.

@abitmore what exactly is the issue with voting?

**Comment by abitmore** [comment] 2016-01-28 20:30
Because the default memo key of collateral-holder account is not valid. It's able to vote after updated to a valid key. It's able to update owner_key and active_key as well. I hadn't realized this when submitting this issue. I think it can be closed.

By the way, when will the "generate key" feature be in GUI? I think I've seen it somewhere..

**Comment by svk31** [comment] 2016-01-28 20:55
OK I noticed the memo key was not valid, but that's not really a GUI issue. If it's possible to update it to a valid one then that should be ok then.

No idea about the "generate key" but I think you're right, and @valzav maybe had an issue open for that.

**Comment by xeroc** [comment] 2016-01-29 10:10
@svk31 
It seems your last patch fixed that issue .. I do have a valid permission for one of my usd-collateral accounts. It states a BTS address instead of a pubkey or account name which is fine for the blockchain and now also for the GUI.

However, when trying to update the proxy I get this error:

```
Unhandled promise rejection Error: account_update.new_options    cause: account_options.memo_key     cause: value required  null 
 stack: _my.required@webpack:///../dl/src/chain/serializer_validation.coffee?:30:1
Types.public_key.toObject@webpack:///../dl/src/chain/serializer_types.coffee?:849:5
Serializer.prototype.toObject@webpack:///../dl/src/chain/serializer.coffee?:105:18
Types.optional/<.toObject@webpack:///../dl/src/chain/serializer_types.coffee?:674:74
Serializer.prototype.toObject@webpack:///../dl/src/chain/serializer.coffee?:105:18
Types.static_variant/<.toObject@webpack:///../dl/src/chain/serializer_types.coffee?:731:24
_my.signed_transaction/<.set_required_fees/operations<@webpack:///../dl/src/chain/signed_transaction.coffee?:103:25
_my.signed_transaction/<.set_required_fees@webpack:///../dl/src/chain/signed_transaction.coffee?:97:21
process_transaction/<@webpack:///../dl/src/stores/WalletDb.js?:162:24
notify/</run@webpack:///./~/babel-core/~/core-js/modules/es6.promise.js?:104:47
notify/<@webpack:///./~/babel-core/~/core-js/modules/es6.promise.js?:115:28
flush@webpack:///./~/babel-core/~/core-js/modules/$.microtask.js?:19:5

 stack: @webpack:///../dl/src/common/error_with_cause.coffee?:28:11
Serializer.prototype.toObject@webpack:///../dl/src/chain/serializer.coffee?:116:7
Types.optional/<.toObject@webpack:///../dl/src/chain/serializer_types.coffee?:674:74
Serializer.prototype.toObject@webpack:///../dl/src/chain/serializer.coffee?:105:18
Types.static_variant/<.toObject@webpack:///../dl/src/chain/serializer_types.coffee?:731:24
_my.signed_transaction/<.set_required_fees/operations<@webpack:///../dl/src/chain/signed_transaction.coffee?:103:25
_my.signed_transaction/<.set_required_fees@webpack:///../dl/src/chain/signed_transaction.coffee?:97:21
process_transaction/<@webpack:///../dl/src/stores/WalletDb.js?:162:24
notify/</run@webpack:///./~/babel-core/~/core-js/modules/es6.promise.js?:104:47
notify/<@webpack:///./~/babel-core/~/core-js/modules/es6.promise.js?:115:28
flush@webpack:///./~/babel-core/~/core-js/modules/$.microtask.js?:19:5

Stack trace:
@webpack:///../dl/src/common/error_with_cause.coffee?:28:11
Serializer.prototype.toObject@webpack:///../dl/src/chain/serializer.coffee?:116:7
Types.static_variant/<.toObject@webpack:///../dl/src/chain/serializer_types.coffee?:731:24
_my.signed_transaction/<.set_required_fees/operations<@webpack:///../dl/src/chain/signed_transaction.coffee?:103:25
_my.signed_transaction/<.set_required_fees@webpack:///../dl/src/chain/signed_transaction.coffee?:97:21
process_transaction/<@webpack:///../dl/src/stores/WalletDb.js?:162:24
notify/</run@webpack:///./~/babel-core/~/core-js/modules/es6.promise.js?:104:47
notify/<@webpack:///./~/babel-core/~/core-js/modules/es6.promise.js?:115:28
flush@webpack:///./~/babel-core/~/core-js/modules/$.microtask.js?:19:5
```

**Comment by svk31** [comment] 2016-01-29 12:26
I think that's the error abit was talking about, the collateral-holders accounts have an invalid memo key, so you need to change it before voting.

`cause: account_options.memo_key     cause: value required  null`

The BTS address is what's in the address_authority array so that's normal, however I added a address -> pubkey -> private key lookup that I was hoping would work, but I see now I didn't quite finish that method. Will push a fix then it would be great if you could look again!

**Comment by xeroc** [comment] 2016-01-29 15:13
Now I am getting 

```
Unhandled promise rejection Error: account_update.new_options     cause: account_options.memo_key     cause: value required  null
```

the permissions page says that `BTS1111111111111111111111111111111114T1Anm` is NOT a valid pubkey.

can't change proxy due to the error above

**Comment by svk31** [comment] 2016-01-29 15:21
Yes, that's why you have to change BTS1111111111111111111111111111111114T1Anm into a valid memo key

**Comment by svk31** [comment] 2016-01-29 16:54
Closing since xeroc has confirmed pubkey lookup works.

**Closed as completed by svk31** 2016-01-29 16:54 UTC
